question_data = {
    "response_code": 0,
    "results": [
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The first IBM PC was released in 1981.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                           "question": "JavaScript derives from a later version of Java",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers", "question": "A Mac is not a PC",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                           "question": "Linux was first created as an alternative to Windows XP.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
         "incorrect_answers": ["False"]}]}
